const QUESTIONS = [
  {
    id: 'f9',
    question: 'Which of the following is NOT a function of the government?',
    answers: ['Establishing Order',
      'Managing Conflicts',
      'Providing Security',
      'Directing Society'],
    correctAnswer: 'Directing Society',
    topic: 'Social Studies',
    hint: 'Which of these should the government probably NOT be doing?',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: ''
  },
  {
    id: 'a0',
    question: 'Mr. Akundo is at the bookstore trying to find a book about History. He cannot see any signs that say "History," but there is a sign that says "Hist."',
    answers: ['Abbrevation',
      'Compound words',
      'Contractions',
      'Suffixes'],
    correctAnswer: 'Abbrevation',
    topic: 'English',
    hint: 'Abbr.',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: 'This second sign is an example of:'
  },
  {
    id: 'a1',
    question: 'Which sentence contains both an idiom AND a homograph?',
    answers: ['Right off the bat, Janey recognized that the habitat she and her team had entered was that of a bat.',
      'You\'ve got all your ducks in a row, kiddo, but it\'s plain to see that old plane will never fly again.',
      'Rain or shine, I\'ll either be late or tardy.',
      'Here\'s the thing about baseball - when you\'re up to bat, you had better take a swing.'],
    correctAnswer: 'Right off the bat, Janey recognized that the habitat she and her team had entered was that of a bat.',
    topic: 'English',
    hint: 'What does each sentence all already have?',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: ''
  },
  {
    id: 'a2',
    question: '"There\'s a man who built a rocket and flew all the way to Mars, where he encountered the Martians. They gave him secret technology for him to bring back to Earth. Then, society rapidly transforms, and finally human armies propel toward the Red Planet."',
    answers: ['Plot',
      'Themes',
      'Conflict',
      'Setting'],
    correctAnswer: 'Plot',
    topic: 'English',
    hint: 'This seems to be about the important events of a story.',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: 'What have you been told mostly about this story?'
  },
  {
    id: 'a3',
    question: 'Which answer best describes the word "conflict" in a fictional story?',
    answers: ['"This is a serious argument or disagreement."',
      '"Two or more of the main characters have to fight it out."',
      '"My sister and I are total opposites."',
      '"You are rich and generous. Give me some money. Thanks!"'],
    correctAnswer: '"Two or more of the main characters have to fight it out."',
    topic: 'English',
    hint: 'How is conflict used specifically in storytelling?',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: ''
  },
  {
    id: 'a4',
    question: 'President Barack Obama very often when speaking publically will use the word "folk." Folks like us, folks back home, the folks we see every day going to work, etc.',
    answers: ['Normal, everyday people.',
      'Friends and neighbors.',
      'African-Americans.',
      'Musicians.'],
    correctAnswer: 'Normal, everyday people.',
    topic: 'English',
    hint: 'What is special about folktales and their audience?',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: 'Which answer best describes how folk was being used?'
  },
  {
    id: 'a5',
    question: '"How difficult the task to quench the fire and the pride of private ambition, and to sacrifice ourselves and all our hopes and expectations to the public weal!"',
    answers: ['Individualism',
      'Inventiveness',
      'Justice',
      'Equality'],
    correctAnswer: 'Individualism',
    topic: 'Social Studies',
    hint: 'What does it sound like was bothering Mrs. Adams when she said this?',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: 'Which word best describes the meaning of this quote from First Lady Abigail Adams?'
  },
  {
    id: 'a6',
    question: 'Albert Einstein is known for many things, but he is probably most famous for his:',
    answers: ['Inventiveness',
      'Seriousness',
      'Famousness',
      'Silliness'],
    correctAnswer: 'Inventiveness',
    topic: 'Social Studies',
    hint: 'E = mc²',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: ''
  },
  {
    id: 'a7',
    question: 'Why is it so important to society that people are good citizens?',
    answers: ['A society is the sum of its citizens.',
      'Nobody likes a bad citizen.',
      'If you\'re not a good citizen, you go to jail.',
      'What goes around comes around.'],
    correctAnswer: 'A society is the sum of its citizens.',
    topic: 'Social Studies',
    TEKS: '10a',
    hint: 'Read carefully: the question asks why it is important to -- society',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: ''
  },
  {
    id: 'a8',
    question: 'Which of the following choices does NOT describe Abigail Adams?',
    answers: ['Wife of John Quincy Adams, the sixth U.S. President.',
      'Her letters are an important document of American Revolutionary history.',
      'Some consider her to be one of the Founders of the United States.',
      'She was one of the most educated people of her time.'],
    correctAnswer: 'Wife of John Quincy Adams, the sixth U.S. President.',
    topic: 'Social Studies',
    TEKS: '10b',
    hint: 'There were two "President Adams"...',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: ''
  },
  {
    id: 'a9',
    question: 'During World War II, the Women Airforce Service Pilots (WASPs) flew over 60 million miles on military missions normally done by men.',
    answers: ['Freedom',
      'Individualism',
      'Inventiveness',
      'Equality'],
    correctAnswer: 'Equality',
    topic: 'Social Studies',
    TEKS: '10b',
    hint: 'Did a lot of women fly planes before the WASPs?',
    viewCt: 0,
    correctCt: 0,
    wrongCt: 0,
    score: 2,
    subquestion: 'Which answer best describes what made the WASPs remebered in history?'
  }
  // ,
  // {
  //   id: 'aa',
  //   question: 'Who were the Navajo Code Talkers?',
  //   answers: ['Cras justo odio',
  //     'Dapibus ac facilisis in',
  //     'Vestibulum at eros',
  //     'Yorfinstein fuf yud'],
  //   correctAnswer: 'Dapibus ac facilisis in',
  //   topic: 'English',
  //   hint: 'etc., Mr. and Mrs.',
  //   viewCt: 0,
  //   correctCt: 0,
  //   wrongCt: 0,
  //   score: 2,
  //   subquestion: ''
  // },
  // {
  //   id: 'ab',
  //   question: 'Who was Sojourner Truth?',
  //   answers: ['Cras justo odio',
  //     'Dapibus ac facilisis in',
  //     'Vestibulum at eros',
  //     'Yorfinstein fuf yud'],
  //   correctAnswer: 'Vestibulum at eros',
  //   topic: 'English',
  //   hint: 'etc., Mr. and Mrs.',
  //   viewCt: 0,
  //   correctCt: 0,
  //   wrongCt: 0,
  //   score: 2,
  //   subquestion: ''
  // },
  // {
  //   id: 'ac',
  //   question: 'What are the three functions of Government?',
  //   answers: ['Cras justo odio',
  //     'Dapibus ac facilisis in',
  //     'Vestibulum at eros',
  //     'Yorfinstein fuf yud'],
  //   correctAnswer: 'Vestibulum at eros',
  //   topic: 'English',
  //   hint: 'etc., Mr. and Mrs.',
  //   viewCt: 0,
  //   correctCt: 0,
  //   wrongCt: 0,
  //   score: 2,
  //   subquestion: ''
  // },
  // {
  //   id: 'ad',
  //   question: 'apostrophe',
  //   answers: ['Cras justo odio',
  //     'Dapibus ac facilisis in',
  //     'Vestibulum at eros',
  //     'Yorfinstein fuf yud'],
  //   correctAnswer: 'Vestibulum at eros',
  //   topic: 'English',
  //   hint: 'etc., Mr. and Mrs.',
  //   viewCt: 0,
  //   correctCt: 0,
  //   wrongCt: 0,
  //   score: 2,
  //   subquestion: ''
  // }
]

export default QUESTIONS